# Generated by Django 5.1 on 2026-05-30 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_whatsappotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='device_fingerprint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pin_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='security_pin',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
