# Generated by Django 5.1 on 2026-06-02 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_profile_device_fingerprint_profile_pin_set_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('kelas', 'Kelas Online'), ('konsultasi', 'Konsultasi'), ('taaruf', "Ta'aruf"), ('artikel', 'Artikel'), ('harga', 'Harga & Promo'), ('akun', 'Akun & Login'), ('umum', 'Umum')], default='umum', max_length=20)),
                ('keywords', models.TextField(help_text='Kata kunci dipisah koma (contoh: kelas, kursus, belajar)')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('button_text', models.CharField(blank=True, help_text='Teks tombol (opsional)', max_length=50, null=True)),
                ('button_icon', models.CharField(blank=True, help_text='Emoji icon (contoh: 📚)', max_length=10, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ Chatbot',
                'verbose_name_plural': 'FAQ Chatbot',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('intent', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
