"""
Django settings for famaline project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4%lb!*4vjb62_fj^bmwse4%lcc85s1wbk26y67bm4uh@f%&4sz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party
    'social_django',
    'crispy_forms',
    'crispy_tailwind',
    # Local apps
    'apps.core',
    'apps.accounts',
    'apps.konsultasi',
]

# ========== GLOBAL RATE LIMIT ==========
GLOBAL_RATE_LIMIT = {
    'MAX_REQUESTS': 100,        # Maksimal 100 request
    'TIME_WINDOW': 60,          # Dalam 60 detik (1 menit)
    'BLOCK_DURATION': 300,      # Blokir 5 menit jika melebihi
}

# Rate limit berdasarkan endpoint
ENDPOINT_RATE_LIMITS = {
    'login': {'max': 10, 'window': 60, 'block': 300},
    'register': {'max': 5, 'window': 300, 'block': 600},
    'send_otp': {'max': 5, 'window': 300, 'block': 600},
    'verify_otp': {'max': 10, 'window': 60, 'block': 300},
    'verify_pin': {'max': 10, 'window': 60, 'block': 300},
    'api': {'max': 100, 'window': 60, 'block': 300},
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.core.rate_limit_global.GlobalRateLimitMiddleware',  # TAMBAHKAN INI (paling bawah)
    'apps.core.middleware.ManageArtikelAuthMiddleware',
]

ROOT_URLCONF = 'famaline.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'famaline.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'cache_table',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Authentication
AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.getenv('GOOGLE_OAUTH2_KEY', '')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.getenv('GOOGLE_OAUTH2_SECRET', '')
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = ['email', 'profile']

LOGIN_URL = '/auth/login/'
LOGIN_REDIRECT_URL = 'core:index'
LOGOUT_REDIRECT_URL = 'core:index'
# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

# Internationalization
LANGUAGE_CODE = 'id'
TIME_ZONE = 'Asia/Jakarta'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"
CRISPY_TEMPLATE_PACK = "tailwind"

# Fonnte WhatsApp Configuration
FONNTE_API_KEY = os.getenv('FONNTE_API_KEY', '')
FONNTE_BASE_URL = os.getenv('FONNTE_BASE_URL', 'https://api.fonnte.com')

# Midtrans Configuration
MIDTRANS_SERVER_KEY = os.getenv('MIDTRANS_SERVER_KEY', '')
MIDTRANS_CLIENT_KEY = os.getenv('MIDTRANS_CLIENT_KEY', '')
MIDTRANS_IS_PRODUCTION = os.getenv('MIDTRANS_IS_PRODUCTION', 'False') == 'True'
MIDTRANS_MERCHANT_ID = os.getenv('MIDTRANS_MERCHANT_ID', '')

# Base URL
BASE_URL = os.getenv('BASE_URL', 'http://127.0.0.1:8000')

# Payment settings
PAYMENT_SUCCESS_URL = f"{BASE_URL}/payment/success/"
PAYMENT_FAILED_URL = f"{BASE_URL}/payment/failed/"
PAYMENT_NOTIFICATION_URL = f"{BASE_URL}/api/midtrans/notification/"
MANAGE_ARTIKEL_PASSWORD = os.getenv('MANAGE_ARTIKEL_PASSWORD', '')
# settings.py
FONNTE_SENDER_NAME = os.getenv('FONNTE_SENDER_NAME', '')


# settings.py - Tambahkan konfigurasi email

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # atau smtp server lain
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'chandraramadhan755@gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'CHANDRARAMADHANCHANDRARAMADHAN')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@famaline.com')

# Untuk development (tanpa email sungguhan)
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Aktifkan HTTPS redirect
#SECURE_SSL_REDIRECT = True

# Cookie keamanan
#SESSION_COOKIE_SECURE = True      # Session hanya via HTTPS
#CSRF_COOKIE_SECURE = True         # CSRF token hanya via HTTPS
#SESSION_COOKIE_HTTPONLY = True    # Tidak bisa diakses JavaScript
#CSRF_COOKIE_HTTPONLY = True       # CSRF tidak bisa diakses JS

# HSTS (HTTP Strict Transport Security)
SECURE_HSTS_SECONDS = 31536000     # 1 tahun
#SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Header keamanan lainnya
SECURE_BROWSER_XSS_FILTER = True   # XSS protection
SECURE_CONTENT_TYPE_NOSNIFF = True # Mencegah MIME sniffing
X_FRAME_OPTIONS = 'DENY'           # Mencegah clickjacking

# Social Auth
SOCIAL_AUTH_SESSION_EXPIRATION = False  # Jangan expire session saat OAuth
SOCIAL_AUTH_GOOGLE_OAUTH2_USE_UNIQUE_USER_ID = True

# Session harus disimpan di setiap request agar state tidak hilang
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_SAMESITE = 'Lax'  # Sudah benar, pastikan ini ada
